// Cross-impl ECDH KAT generator (ADR-0011 P3 / ESP-FW-6, step 1).
//
// Emits a golden vector for the secp256k1 ECDH shared-secret X-coordinate using
// TWO independent reference implementations that must agree:
//   1. node:crypto createECDH('secp256k1')  -> OpenSSL  (authoritative)
//   2. @noble/curves getSharedSecret(...)    -> the reader/browser library
// micro-ecc (firmware) is then checked against this vector by kat_ecdh.c.
//
// Output: kat_vectors.h (C arrays for the host harness) + kat_vectors.json.
// Fixed test keys (both < n, nonzero) — NOT real device/owner keys.

import crypto from 'node:crypto';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));

const DEV_PRIV   = '4c0883a69102937d6231471b5dbb6204fe5129617082792ae468d01a3f362318';
const OWNER_PRIV = '2bdd5d8b3e1a2c3d4e5f60718293a4b5c6d7e8f90a1b2c3d4e5f607182930405';

const hex = (b) => Buffer.from(b).toString('hex');
const eq  = (a, b) => Buffer.from(a).equals(Buffer.from(b));

function ecdh(privHex) {
  const e = crypto.createECDH('secp256k1');
  e.setPrivateKey(Buffer.from(privHex, 'hex'));
  return e;
}

const dev = ecdh(DEV_PRIV);
const own = ecdh(OWNER_PRIV);

const devPubU   = dev.getPublicKey(null, 'uncompressed'); // 0x04 || X || Y (65)
const ownPubU   = own.getPublicKey(null, 'uncompressed');
const devPub64  = devPubU.subarray(1);                    // X || Y (64)
const ownPub64  = ownPubU.subarray(1);

const sharedDevOwn = dev.computeSecret(ownPubU);          // X(dev_priv * owner_pub)
const sharedOwnDev = own.computeSecret(devPubU);          // X(owner_priv * dev_pub)
if (!eq(sharedDevOwn, sharedOwnDev)) {
  console.error('FATAL: OpenSSL ECDH not symmetric'); process.exit(2);
}
const SHARED_X = sharedDevOwn;

// --- independent cross-check vs @noble/curves (the reader's lib) ---
let nobleStatus = 'skipped (NOBLE_PATH unset)';
if (process.env.NOBLE_PATH) {
  try {
    const { secp256k1 } = await import(process.env.NOBLE_PATH);
    const ns = secp256k1.getSharedSecret(DEV_PRIV, hex(ownPubU), false).subarray(1, 33);
    if (!eq(ns, SHARED_X)) {
      console.error('FATAL: @noble/curves disagrees with OpenSSL ECDH');
      console.error(' noble :', hex(ns));
      console.error(' openssl:', hex(SHARED_X));
      process.exit(3);
    }
    nobleStatus = 'MATCH (@noble/curves == OpenSSL)';
  } catch (e) {
    nobleStatus = 'error: ' + e.message;
  }
}

const cArr = (name, buf) =>
  `static const uint8_t ${name}[${buf.length}] = {\n` +
  Array.from(buf).map((x, i) => `0x${x.toString(16).padStart(2, '0')}` + (i % 12 === 11 ? ',\n' : ','))
    .join('').replace(/,\n,/g, ',\n').replace(/,$/, '') +
  `\n};\n`;

const header =
`/* AUTO-GENERATED by gen_kat.mjs — DO NOT EDIT. ECDH golden vector (ADR-0011 P3).
 * dev_priv   = ${DEV_PRIV}
 * owner_priv = ${OWNER_PRIV}
 * shared_x   = ${hex(SHARED_X)}
 * reference  = node:crypto OpenSSL (symmetric-checked); noble: ${nobleStatus}
 */
#pragma once
#include <stdint.h>

${cArr('kat_dev_priv', Buffer.from(DEV_PRIV, 'hex'))}
${cArr('kat_owner_priv', Buffer.from(OWNER_PRIV, 'hex'))}
${cArr('kat_dev_pub', devPub64)}
${cArr('kat_owner_pub', ownPub64)}
${cArr('kat_expected_shared_x', SHARED_X)}`;

writeFileSync(join(HERE, 'kat_vectors.h'), header);

// ---------------------------------------------------------------- HKDF (step 2)
// Mirrors apps/api credentials.ts: salt = `${owner}|${devicePubkey}` (lowercased),
// info = `w3pups-arkiv-${PURPOSE}|epoch=${decimal}`. IKM = the ECDH shared_x above.
// The owner address here is a fixed sample (HKDF only cares about the salt bytes;
// the addr==keccak(ownerPub) binding is enforced elsewhere, not by this KAT).
const OWNER_ADDR = '0x9f8e7d6c5b4a39281706f5e4d3c2b1a09f8e7d6c';
const EPOCH = 7;
const PURPOSE = 'telemetry';
const saltStr = `${OWNER_ADDR.toLowerCase()}|${hex(devPub64).toLowerCase()}`;
const infoStr = `w3pups-arkiv-${PURPOSE}|epoch=${EPOCH}`;
const OKM = crypto.hkdfSync('sha256', SHARED_X,
  Buffer.from(saltStr, 'utf8'), Buffer.from(infoStr, 'utf8'), 32);
const OKM_B = Buffer.from(OKM); // hkdfSync returns ArrayBuffer

const hkdfHeader =
`/* AUTO-GENERATED by gen_kat.mjs — DO NOT EDIT. HKDF-SHA256 golden vector (ADR-0011 P3).
 * ikm  = shared_x (ECDH, above)
 * salt = "${saltStr}"
 * info = "${infoStr}"
 * okm  = ${hex(OKM_B)}   (reference: node crypto.hkdfSync)
 */
#pragma once
#include <stdint.h>
#include <stddef.h>

${cArr('kat_hkdf_ikm', SHARED_X)}
static const char kat_hkdf_salt[] = "${saltStr}";
static const char kat_hkdf_info[] = "${infoStr}";
${cArr('kat_hkdf_expected_okm', OKM_B)}`;

writeFileSync(join(HERE, 'hkdf_vectors.h'), hkdfHeader);

// ----------------------------------------------------------- AES-256-GCM (step 3)
// key = the HKDF OKM (the real K_dir); fixed nonce/aad/pt. node:crypto reference.
const GCM_KEY = OKM_B;
const GCM_NONCE = Buffer.from('03014000000000000000002a', 'hex'); // 12B sample
const GCM_AAD = Buffer.from('type=w3pups-telemetry|epoch=7|dev=8988228066614189920', 'utf8');
const GCM_PT = Buffer.concat([Buffer.from('Web3PiUPS-GCM-KAT', 'utf8'), Buffer.from([0x00, 0x01, 0xff, 0x7f])]);
const ci = crypto.createCipheriv('aes-256-gcm', GCM_KEY, GCM_NONCE);
ci.setAAD(GCM_AAD);
const GCM_CT = Buffer.concat([ci.update(GCM_PT), ci.final()]);
const GCM_TAG = ci.getAuthTag();

const gcmHeader =
`/* AUTO-GENERATED by gen_kat.mjs — DO NOT EDIT. AES-256-GCM golden vector (ADR-0011 P3).
 * key(=HKDF okm) = ${hex(GCM_KEY)}
 * nonce          = ${hex(GCM_NONCE)}
 * tag            = ${hex(GCM_TAG)}   (reference: node:crypto aes-256-gcm)
 */
#pragma once
#include <stdint.h>

${cArr('kat_gcm_key', GCM_KEY)}
${cArr('kat_gcm_nonce', GCM_NONCE)}
${cArr('kat_gcm_aad', GCM_AAD)}
${cArr('kat_gcm_pt', GCM_PT)}
${cArr('kat_gcm_ct', GCM_CT)}
${cArr('kat_gcm_tag', GCM_TAG)}`;

writeFileSync(join(HERE, 'gcm_vectors.h'), gcmHeader);

// ----------------------------------------------------------- full SEAL (step 4)
// This JS is ALSO the byte-exact spec the browser decryptor (step 12) implements.
function deriveKdir(purpose, epoch) {
  const salt = `${OWNER_ADDR.toLowerCase()}|${hex(devPub64).toLowerCase()}`;
  const info = `w3pups-arkiv-${purpose}|epoch=${epoch}`;
  return Buffer.from(crypto.hkdfSync('sha256', SHARED_X,
    Buffer.from(salt, 'utf8'), Buffer.from(info, 'utf8'), 32));
}
function packNonce(typeTag, epoch, seq) {
  const n = Buffer.alloc(12);
  n[0] = 0x03; n[1] = typeTag;
  n.writeUInt32BE(epoch >>> 0, 2);
  const s = Buffer.alloc(8); s.writeBigUInt64BE(BigInt(seq));
  s.subarray(2).copy(n, 6);          // low 48 bits of seq, big-endian
  return n;
}
function sealJS(typeTag, purpose, epoch, seq, deviceId, entity, cmdId, pt) {
  const kdir = deriveKdir(purpose, epoch);
  const nonce = packNonce(typeTag, epoch, seq);
  const parts = [nonce, Buffer.from(deviceId, 'utf8'), Buffer.from(entity, 'utf8')];
  if (cmdId) parts.push(Buffer.from(cmdId, 'utf8'));
  const aad = Buffer.concat(parts);
  const c = crypto.createCipheriv('aes-256-gcm', kdir, nonce); c.setAAD(aad);
  const ct = Buffer.concat([c.update(pt), c.final()]); const tag = c.getAuthTag();
  return { kdir, body: Buffer.concat([nonce, ct, tag]) };
}

const DEVID = '8988228066614189920';
const TLM = sealJS(0x01, 'telemetry', 7, 1234, DEVID, 'w3pups-telemetry', null,
  Buffer.from('TLM:vbus=12.34,soc=87,flags=0x1', 'utf8'));
const ACK = sealJS(0x02, 'ack', 7, 1235, DEVID, 'w3pups-ack',
  '550e8400-e29b-41d4-a716-446655440000', Buffer.from([0x01, 0x00, 0x2a, 0xff]));
const CMDID = '550e8400-e29b-41d4-a716-446655440000';
const TLM_PT = Buffer.from('TLM:vbus=12.34,soc=87,flags=0x1', 'utf8');
const ACK_PT = Buffer.from([0x01, 0x00, 0x2a, 0xff]);

const sealHeader =
`/* AUTO-GENERATED by gen_kat.mjs — DO NOT EDIT. Full Arkiv seal golden vector (ADR-0011 P3).
 * This is the byte-exact wire contract the browser decryptor must reproduce.
 * salt = "${OWNER_ADDR.toLowerCase()}|<devpub128>", info = "w3pups-arkiv-<purpose>|epoch=<dec>"
 * tlm body = ${hex(TLM.body)}
 */
#pragma once
#include <stdint.h>

${cArr('seal_shared_x', SHARED_X)}
static const char seal_owner_lower[]  = "${OWNER_ADDR.toLowerCase()}";
static const char seal_devpub_lower[] = "${hex(devPub64).toLowerCase()}";
static const char seal_device_id[]    = "${DEVID}";

/* telemetry */
#define SEAL_TLM_TYPETAG 0x01
#define SEAL_TLM_EPOCH   7u
#define SEAL_TLM_SEQ     1234ULL
static const char seal_tlm_entity[] = "w3pups-telemetry";
${cArr('seal_tlm_pt', TLM_PT)}
${cArr('seal_tlm_kdir', TLM.kdir)}
${cArr('seal_tlm_body', TLM.body)}

/* ack (command_id bound into AAD) */
#define SEAL_ACK_TYPETAG 0x02
#define SEAL_ACK_EPOCH   7u
#define SEAL_ACK_SEQ     1235ULL
static const char seal_ack_entity[] = "w3pups-ack";
static const char seal_ack_cmdid[]  = "${CMDID}";
${cArr('seal_ack_pt', ACK_PT)}
${cArr('seal_ack_kdir', ACK.kdir)}
${cArr('seal_ack_body', ACK.body)}`;

writeFileSync(join(HERE, 'seal_vectors.h'), sealHeader);

writeFileSync(join(HERE, 'kat_vectors.json'), JSON.stringify({
  dev_priv: DEV_PRIV, owner_priv: OWNER_PRIV,
  dev_pub: hex(devPub64), owner_pub: hex(ownPub64),
  shared_x: hex(SHARED_X), noble: nobleStatus,
  hkdf: { salt: saltStr, info: infoStr, ikm: hex(SHARED_X), okm: hex(OKM_B) },
  gcm: { key: hex(GCM_KEY), nonce: hex(GCM_NONCE), aad: hex(GCM_AAD),
         pt: hex(GCM_PT), ct: hex(GCM_CT), tag: hex(GCM_TAG) },
  seal: {
    owner_addr: OWNER_ADDR.toLowerCase(),
    device_pubkey: hex(devPub64).toLowerCase(),
    shared_x: hex(SHARED_X),
    telemetry: { typeTag: 1, purpose: 'telemetry', epoch: 7, seq: 1234,
      device_id: DEVID, entity_type: 'w3pups-telemetry',
      kdir: hex(TLM.kdir), pt: hex(TLM_PT), body: hex(TLM.body) },
    ack: { typeTag: 2, purpose: 'ack', epoch: 7, seq: 1235,
      device_id: DEVID, entity_type: 'w3pups-ack', command_id: CMDID,
      kdir: hex(ACK.kdir), pt: hex(ACK_PT), body: hex(ACK.body) },
  },
}, null, 2) + '\n');

console.log('reference shared_x =', hex(SHARED_X));
console.log('noble cross-check  =', nobleStatus);
console.log('reference hkdf okm =', hex(OKM_B));
console.log('reference gcm tag  =', hex(GCM_TAG));
console.log('reference seal body=', hex(TLM.body));
console.log('wrote kat_vectors.h + hkdf_vectors.h + gcm_vectors.h + seal_vectors.h + kat_vectors.json');
